DROP DATABASE IF EXISTS burgers_db;
CREATE DATABASE tasks_db;


USE tasks_db;

CREATE TABLE tasks
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	task VARCHAR (255) NOT NULL,
    completed BOOLEAN
);

